= Conclusion <sec:conclusion>

This paper has presented three orientation-selective edge detection filters, a fused polynomial stencil, a rectangular Gaussian kernel, and an elliptical Gaussian kernel, unified under a common GPU-accelerated framework that reduces each variant to a single gather-dot-product operation per pixel per orientation. The progression from the first to the third was driven not by arbitrary design choices but by structural insight exposed through algebraic fusion. Collapsing the multi-step Line Filter pipeline into a single precomputed weight vector revealed that approximately 28% of the total weight budget is consumed by near-zero entries arising from overlapping polynomial neighborhoods with opposing sign contributions. This cancellation is invisible in the unfused formulation and represents a fundamental limitation of the tile-and-sum construction, not a correctable implementation artifact.

The geometric kernels proposed in this work avoid weight cancellation entirely by defining the anisotropic envelope directly from an analytic spatial function rather than assembling it from shifted polynomial fits. Rectangular and elliptical Gaussian envelopes assign every gathered pixel a purposeful, non-negative weight, eliminating wasted degrees of freedom and producing smoother, more interpretable weight distributions. Viewed historically, this trajectory is a natural one. The Weighted Vector Filter and Line Filter belong to a lineage extending from the one-dimensional Savitzky--Golay filter @savitzky1964smoothing through its two-dimensional generalizations @luo2005savitzkygolay2d, steerable filters @freeman1991steerable, and anisotropic Gaussian derivatives @geusebroek2003fast. The geometric kernels introduced here are the logical endpoint of that lineage, retaining the coupled smoothing-and-differentiation property that makes polynomial fitting attractive while replacing the polynomial machinery with the simplest possible spatial definition.

The empirical results support three main findings. The fused polynomial stencil achieves a $24 times$ wall-clock speedup and a $311 times$ reduction in VRAM consumption relative to the naive LF implementation while producing bit-identical output. The geometric kernels provide a further $3 times$ speedup beyond the fused stencil and match its accuracy to within 0.3% ODS F-score, with efficiency ratios above $eta > 0.99$ compared to $eta approx 0.72$ for the polynomial construction. All three ASF variants outperform every one of the 54 classical baseline configurations evaluated on every benchmark. Against deep learning models, the ASF approaches but does not match state-of-the-art performance on clean imagery, yet overtakes all five deep learning baselines under additive noise at $"SNR" <= 5 "dB"$, a regime that is common in practical deployment but absent from standard training sets. The parameter ablation spanning more than 1,200 configurations across 330 images confirms that no single parameter setting dominates universally; the optimal combination of polynomial order, neighborhood radius, line length, and orientation count is condition-dependent, underscoring the value of efficient GPU execution that makes large-scale sweeps practical.

Several directions remain open. The most immediate is automatic parameter selection, in which the kernel shape parameters $sigma_u$ and $sigma_v$ would be set adaptively from local image statistics rather than fixed globally. A second direction is to retain the gather-dot-product computational architecture while replacing the analytic envelope with a learned envelope function optimized end-to-end on annotated data, combining the structural transparency of the present approach with the representational flexibility of deep learning. Third, the current single-frame execution time of approximately 45 ms suggests feasibility for real-time video edge detection, provided that temporal coherence constraints are incorporated to suppress flicker across frames. Finally, alternative polynomial bases such as Zernike or Legendre polynomials may offer better conditioning or rotational symmetry properties than the Taylor monomial basis used throughout this work.
