= Introduction <sec:introduction>

Edge detection remains one of the most fundamental operations in computer vision. It underpins object recognition pipelines, drives contour-based image segmentation, enables autonomous navigation through structured environments, and provides the geometric primitives on which industrial inspection and dimensional measurement systems depend @canny1986edge @bhardwaj2012edge. Despite more than five decades of sustained research, the design of edge detection operators continues to be governed by a three-way tension between noise robustness, spatial precision, and computational cost. Increasing the spatial support of a gradient estimator improves its resilience to noise, but at the expense of blurring fine structural detail and increasing the number of arithmetic operations per pixel. No single operator has resolved this trade-off universally, and the history of the field can be read as a succession of attempts to shift the balance.

The earliest and still most widely deployed gradient operators are the small fixed-kernel convolutions introduced in the 1960s and 1970s. The Roberts Cross operator @roberts1963machine estimates gradients along two diagonal directions using a $2 times 2$ stencil. The Prewitt filter @prewitt1970gradient and the Sobel filter @sobel2014history extend the support region to $3 times 3$, incorporating a modest smoothing component orthogonal to the differentiation axis. These operators are trivially fast, require no tunable parameters, and are available in every major image-processing library. Their small spatial support, however, is also their principal limitation. With only nine pixels contributing to each gradient estimate, any noise within the window directly corrupts the output. Extending the kernel to $5 times 5$ or $7 times 7$ yields marginal improvement, but the hand-designed weight structures remain fixed and cannot adapt to the local edge orientation or the prevailing noise level in a given image region.

The Canny detector @canny1986edge addressed the noise sensitivity of small kernels by introducing a multi-stage pipeline. A Gaussian pre-smoothing step suppresses high-frequency noise before gradient computation, and subsequent non-maximum suppression and hysteresis thresholding stages refine the detected contours into thin, connected edge maps. The Canny detector became the dominant classical method and remains a standard baseline in the literature. Nevertheless, the Gaussian smoothing stage introduces a fundamental trade-off between denoising strength and localization accuracy. Stronger smoothing suppresses more noise but simultaneously displaces weak edges and low-contrast boundaries from their true positions. Furthermore, because the smoothing and differentiation stages are decoupled by design, the gradient orientation at each pixel is computed from an arctangent of two cardinal finite differences, propagating quantization and noise errors from the $x$ and $y$ channels into every intermediate angle estimate. These limitations are well documented but difficult to overcome within the Canny framework.

The past decade has seen a decisive shift toward deep learning approaches for boundary detection. Holistically-Nested Edge Detection (HED) @xie2015hed demonstrated that a fully convolutional network with multi-scale side outputs could learn rich boundary representations from human-annotated ground truth. Subsequent architectures have pushed benchmark scores steadily higher. DexiNed @poma2020dexined introduced dense extreme inception blocks that enable training from scratch without ImageNet pre-training. PiDiNet @su2021pidinet integrated classical pixel-difference convolutions into a lightweight network architecture. TEED @soria2023teed achieved competitive accuracy with an extremely compact model of only 58K parameters. More recently, NBED @chen2024nbed and DiffusionEdge @ye2024diffusionedge have explored negative-sample bootstrapping and diffusion-based generative modeling to further improve boundary recall. These methods routinely achieve Optimal Dataset Scale (ODS) F-scores above 0.80 on the BSDS500 benchmark @arbelaez2011bsds500, substantially outperforming all classical operators on that dataset. However, the reliance on supervised training introduces practical constraints that are difficult to ignore. Deep models require large corpora of pixel-level edge annotations, which are expensive to produce and inherently subjective @dollar2013structured. More critically, models trained on natural photographic imagery generalize poorly when deployed in domains whose intensity statistics diverge significantly from the training distribution. Underwater imagery, medical scans, thermal infrared sequences, and synthetic-aperture radar all present noise characteristics that are poorly represented in standard benchmarks @schettini2010underwater @goodman1976speckle. Re-training or fine-tuning for each new domain negates the convenience that motivates a general-purpose detector. Finally, learned operators produce edge probability maps rather than calibrated derivative estimates, making them unsuitable for applications that require quantitative gradient magnitudes or precise orientation angles.

Each generation of methods, then, trades one problem for another. Classical fixed-kernel operators are fast and deterministic but fragile under noise. Multi-stage pipelines like Canny provide better noise handling but blur weak edges and decouple smoothing from differentiation. Deep learning models achieve the highest benchmark scores but depend on training data, generalize poorly across domains, and abandon the notion of a true image derivative.

== The Local Polynomial Fitting Approach <sec:intro-lpf>

An alternative strategy, one that couples smoothing and differentiation into a single principled operation, has been independently reinvented multiple times across disconnected communities over the past six decades. The idea is simple. Rather than convolving the image with a fixed kernel designed by hand, one fits a low-order polynomial to the pixel intensities in a local neighborhood and reads off the desired derivative from the fitted coefficients. Because the polynomial fit is a least-squares operation over a potentially large number of pixels, it provides inherent noise suppression whose strength scales with the neighborhood size. Because the derivative is extracted analytically from the polynomial model, smoothing and differentiation are fused into one step.

Savitzky and Golay @savitzkygolay1964 introduced this approach in 1964 for smoothing and differentiating spectroscopic data. Their key insight was that the least-squares polynomial fit over an equally spaced one-dimensional window can be expressed as a single convolution with precomputed weights, making it no more expensive than a moving average. The method became ubiquitous in analytical chemistry and signal processing. Gorry @gorry1990sg generalized the convolution coefficients to arbitrary derivative orders and non-uniform spacing. Extensions to two-dimensional grids followed. Meer, Baugher, and Rosenfeld @meer1991sg2d analyzed the frequency-domain properties of 2D polynomial fitting kernels for image pyramid generation. Luo _et al._ @luo2005sg2d provided a systematic treatment of two-dimensional Savitzky--Golay digital differentiators, deriving their transfer functions and establishing conditions on the polynomial order and window size needed for accurate derivative estimation on discrete image grids.

In a parallel line of development, Freeman and Adelson @freeman1991steerable solved the problem of orientation-selective filtering analytically by showing that certain filter families can be _steered_ to any arbitrary angle through a linear combination of a small set of basis filters. Steerable filters provide a computationally elegant means of computing directional derivatives without the brute-force cost of evaluating a separate kernel at each candidate orientation. Gaussian derivatives are the canonical example. A first-order Gaussian derivative steered to angle $theta$ is simply the cosine-weighted sum of the $x$- and $y$-derivative basis filters, and the maximum-response orientation can be found in closed form. This framework has been widely adopted in texture analysis, motion estimation, and feature detection.

Geusebroek, Smeulders, and van de Weijer @geusebroek2003aniso built on this foundation by constructing _anisotropic_ Gaussian derivative kernels in which the smoothing envelope is elongated along the edge direction. By decoupling the scale parameters along the normal and tangent axes, their filters can integrate information over a long tangential extent for noise suppression while maintaining a narrow profile in the normal direction for precise localization. The resulting kernels are separable along the principal axes of the elliptical Gaussian, enabling efficient recursive implementation.

Bagan and Wang @bagan2021wvf @bagan2023lf independently arrived at what is, in algebraic terms, a two-dimensional Savitzky--Golay derivative filter applied in a vision context. Their initial formulation, the Weighted Vector Filter (WVF) @bagan2021wvf, fits a two-dimensional Taylor polynomial of degree $d$ to pixels gathered from a circular neighborhood and extracts the gradient from the fitted coefficients, precisely the 2D Savitzky--Golay procedure. Their subsequent extension, the Line Filter (LF) @bagan2023lf, evaluates the point-filter response at multiple virtual positions displaced along each candidate edge direction, effectively constructing an anisotropic support region that is elongated tangentially to the hypothesized boundary. A brute-force sweep over $N_s$ uniformly spaced orientations selects the direction producing the strongest normal derivative. This orientation sweep is a discrete, sampled-angle approximation to the continuous steerability property formalized by Freeman and Adelson three decades earlier. The publications introducing the WVF and LF do not reference the Savitzky--Golay literature, steerable filters, or anisotropic Gaussian derivatives. The connection between these bodies of work appears to have gone entirely unrecognized.

The consequence of this fragmentation is that a natural and productive question has never been posed. If the Line Filter is, at its core, an oriented, line-averaged two-dimensional Savitzky--Golay derivative filter, what is the simplest and fastest formulation that preserves its favorable accuracy characteristics? Conversely, what structural limitations does the polynomial-fitting construction impose, and can alternative kernel geometries avoid those limitations while retaining the same noise-robustness properties?

== Questions and Contributions <sec:intro-contributions>

This paper addresses three specific questions. First, can the multi-step LF pipeline, in which a point filter is repeatedly evaluated at shifted positions along each candidate orientation and the responses are aggregated, be collapsed into a single linear operation suitable for GPU execution? Second, what structural limitations does this algebraic fusion reveal about polynomial-fitting-based kernels? Third, can simpler geometric kernel definitions, such as rectangular and elliptical Gaussian envelopes, match or exceed the accuracy of polynomial fitting while avoiding those limitations?

The contributions are as follows.

+ _Fused stencil formulation._ We show that the entire LF pipeline can be algebraically collapsed into a single precomputed weight vector per orientation, reducing the filter to one gather-multiply-sum operation per pixel. This reformulation eliminates all redundant memory accesses and yields a $24 times$ wall-clock speedup and a $311 times$ reduction in GPU VRAM consumption compared to a naive implementation, while preserving bit-identical output.

+ _Weight cancellation analysis._ The stencil fusion exposes a structural deficiency that is invisible in the unfused pipeline. Because neighboring point-filter evaluations share large fractions of their pixel neighborhoods, many pixels receive contributions from multiple overlapping fits with opposing signs. We demonstrate that approximately 28% of the total weight budget in a typical fused stencil is consumed by pixels whose net weight magnitude is negligible, representing wasted computation and a suboptimal allocation of the filter's effective degrees of freedom.

+ _Geometric kernel alternatives._ We propose two kernel families that define the anisotropic weight envelope directly from an analytic function, bypassing the tile-and-sum construction entirely. A rectangular kernel assigns uniform weight within an oriented bounding box, while an elliptical Gaussian kernel produces a smooth, naturally tapered distribution whose major axis is aligned with the edge tangent. Both alternatives eliminate weight cancellation by construction, match polynomial fitting accuracy to within 0.3% ODS F-score, and execute approximately $3 times$ faster than the fused polynomial stencil.

+ _Comprehensive evaluation._ We evaluate all filter variants across more than 1,200 parameter configurations on three standard benchmarks (BSDS500, BIPED, and UDED), comparing against 54 classical baseline operators and 5 state-of-the-art deep learning models. The evaluation includes noise robustness testing under additive Gaussian corruption at multiple severity levels, providing the most extensive comparative assessment of polynomial-fitting-based edge detectors to date.
