// Section 9: Discussion

= Discussion <sec:discussion>

The experimental results of the preceding sections establish the quantitative performance of the ASF variants relative to both classical and deep learning baselines. This section interprets those results, identifies the broader implications of the fused stencil analysis, and offers practical guidance for selecting a filter variant and parameterization for deployment.


== What the Fused Stencil Reveals About Polynomial Fitting <sec:disc-stencil>

The fused stencil formulation was originally motivated as a computational optimization. By collapsing the multi-step Line Filter pipeline into a single precomputed weight vector per orientation, it eliminated redundant memory accesses and produced a substantial wall-clock speedup. In retrospect, however, the most important contribution of the fusion is not computational but conceptual. The fused stencil strips the polynomial fitting procedure down to its essential output, a set of scalar weights applied to pixel intensities, and in doing so reveals what the polynomial model actually does within the filter.

The Taylor expansion, the least-squares objective, and the Moore--Penrose pseudoinverse are not themselves part of the filtering operation. They are a _weight-generation mechanism_. Once the pseudoinverse has been evaluated and the relevant row extracted, the polynomial model plays no further role. The filter response at each pixel is a single inner product of the precomputed weights with the local intensity values, structurally identical to any other linear convolution kernel. The polynomial surface is never evaluated, its coefficients beyond the first derivative are discarded, and its approximation quality at non-center locations is irrelevant to the edge detection task. The elaborate algebraic machinery exists solely to produce a vector of numbers that multiply pixel values.

This perspective reframes the weight cancellation phenomenon documented in @sec:weight-cancel. When the Line Filter averages multiple shifted point-filter evaluations, the overlapping support regions cause pixels near the center of the stencil to receive contributions from many independent fits. Because the polynomial weights alternate in sign across the differentiation axis, contributions from adjacent fits partially cancel, leaving net weights that are small in magnitude but nonzero. Approximately 28% of the total weight budget is consumed by pixels whose net contribution is negligible. This cancellation is not a numerical artifact or an implementation error. It is a structural consequence of deriving anisotropic weights by tiling and summing isotropic polynomial fits that were never designed with the global stencil geometry in mind.

The geometric kernel variants follow as the natural conclusion of this analysis. If the polynomial model is merely a means of generating weights, and if that particular means produces a weight distribution with known inefficiencies, then the obvious response is to replace the weight-generation mechanism with one that is purpose-designed for the task. Rectangular and elliptical Gaussian envelopes define the anisotropic weight distribution directly from an analytic function, bypassing the tile-and-sum construction entirely. They eliminate weight cancellation by construction, because every pixel in the support region receives a single, positive, intentionally assigned weight. The fact that these simpler kernels match the polynomial variant to within 0.3% ODS F-score confirms that the polynomial model contributed no essential structure beyond what a well-shaped weight envelope provides.


== The Noise--Resolution Tradeoff and Adaptive Filtering <sec:disc-tradeoff>

A fundamental tension governs all gradient estimation. Enlarging the spatial support of the filter averages over more pixels, improving noise robustness, but simultaneously blurs fine spatial detail and displaces detected edges from their true positions. Every edge detector navigates this tradeoff, and the methods surveyed in this paper differ primarily in _when_ and _how_ that navigation occurs.

Classical fixed-kernel operators such as Sobel and Prewitt resolve the tradeoff at design time. Their $3 times 3$ support is baked into the kernel definition and cannot be adjusted at deployment. This rigidity is acceptable when the noise level is known and constant, but it becomes a liability in environments where conditions vary across the image or between acquisitions. Deep learning methods resolve the tradeoff at training time, learning receptive field sizes and feature combinations that are optimal for the distribution of edges and noise present in the training corpus. Once trained, however, the learned tradeoff is equally fixed. A model trained on clean natural images cannot widen its effective support to handle sensor noise at deployment without retraining or fine-tuning, which may be impractical in the field.

The ASF and its geometric kernel variants offer a qualitatively different solution. The parameters $sigma_u$ and $sigma_v$ provide explicit, continuous control over the extent of the weight envelope along the edge normal and tangent directions, respectively. Increasing $sigma_v$ elongates the kernel along the edge, averaging over more tangential pixels to suppress noise without broadening the response perpendicular to the boundary. Increasing $sigma_u$ widens the normal profile, trading localization precision for additional smoothing when the noise floor is high. These parameters can be adjusted at deployment time, between frames, or even spatially within a single image if a local noise estimate is available. This _parametric adaptability_ is the primary practical advantage of the ASF framework over both classical fixed kernels and learned models.


== Why Geometric Kernels Are the Preferred Variant <sec:disc-geom>

The three ASF variants, polynomial, rectangular geometric, and elliptical geometric, achieve ODS F-scores within 0.3% of one another across all three benchmarks. At this level of accuracy parity, the choice among them is properly driven by secondary criteria rather than by detection performance alone.

On every such criterion, the geometric kernels are preferable. They execute approximately $3 times$ faster than the fused polynomial stencil because their support regions contain fewer pixels and require no cancellation-inflated weight vectors. Their weight distributions are fully determined by two or three interpretable parameters ($sigma_u$, $sigma_v$, and the hard cutoff radius for the rectangular variant), whereas the polynomial weights depend on the polynomial order $d$, the neighborhood radius, the line extension length, and their interactions. The noise variance of the geometric kernel response can be expressed in closed form as a function of $sigma_u$ and $sigma_v$, enabling analytic noise scaling predictions that the polynomial variant does not admit. Execution time is constant for a given parameter setting regardless of image content, a property that simplifies real-time scheduling guarantees.

Between the two geometric variants, the rectangular and elliptical kernels present a minor secondary tradeoff. The rectangular kernel achieves a higher effective sample count $N_"eff"$ for a given spatial extent because it assigns uniform weight to all pixels within its support, wasting no weight budget on tapering. The elliptical Gaussian kernel, by contrast, produces a smoother frequency response with lower sidelobes, which can reduce ringing artifacts near high-contrast boundaries. In the benchmarks evaluated here, the rectangular kernel achieves marginally higher F-scores on two of three datasets while executing slightly faster. It is therefore recommended as the default variant for general use, with the elliptical kernel reserved for applications where frequency-domain smoothness is a priority.


== Semantic Versus Photometric Edges <sec:disc-semantic>

The largest performance gap between the ASF variants and deep learning models appears on the BSDS500 benchmark, where the deficit reaches approximately 18.3 ODS F-score points. This gap narrows considerably on BIPED, where it falls to 9--10 points, and nearly vanishes on UDED, where it is approximately 3 points. The pattern is not coincidental and reflects a fundamental distinction between what the two families of methods detect.

BSDS500 ground truth annotations encode _semantic_ boundaries, contours that human annotators judge to be perceptually meaningful. These include boundaries between texture regions that share identical local intensity statistics, occlusion edges inferred from scene context rather than photometric contrast, and illusory contours that have no gradient support whatsoever. Deep learning models, trained on these annotations, learn to recognize such boundaries by leveraging hierarchical features that encode texture, context, and object-level semantics. The ASF, by contrast, measures intensity gradients. It responds to local photometric discontinuities and is structurally incapable of detecting boundaries that are not accompanied by an intensity or color change. The 18.3-point gap on BSDS500 therefore does not indicate that the ASF is a poor edge detector. It indicates that the ASF and the deep models are answering different questions. The ASF asks _where does the image intensity change rapidly_, while the semantic models ask _where do humans perceive object boundaries_. These questions coincide on many edges but diverge on texture boundaries, context-dependent contours, and low-contrast semantic transitions.

The BIPED and UDED datasets contain ground truth that is more closely aligned with photometric discontinuities, which explains the narrower gaps. On UDED in particular, where the task is dominated by clearly defined intensity edges, the ASF performs within 3 points of the best deep models. This result confirms that for photometric edge detection, a well-parameterized gradient operator remains competitive with learned approaches.


== No Single Best Edge Detector <sec:disc-no-best>

A recurring theme throughout the experimental evaluation is the instability of method rankings across conditions. The detector that achieves the highest F-score on clean BSDS500 images is not the same detector that performs best on BIPED or UDED, and rankings invert again when noise is introduced. Several deep models that dominate the clean BSDS500 leaderboard suffer disproportionate accuracy losses under moderate Gaussian corruption, while the ASF variants, whose performance on clean BSDS500 is modest, degrade more gracefully and overtake multiple learned baselines at elevated noise levels.

This instability is not an anomaly to be explained away. It is the expected consequence of the fact that different benchmarks, noise conditions, and application requirements expose different facets of detector behavior. Optimizing for BSDS500 ODS rewards semantic boundary recall at the expense of photometric precision. Optimizing for noise robustness rewards large spatial support at the expense of fine-structure resolution. No single method can simultaneously maximize all of these objectives. The practical implication is that method selection should be _condition-dependent_ rather than _benchmark-dependent_. Reporting a single leaderboard rank as evidence of general superiority is misleading when that rank does not transfer to other datasets or operating conditions.


== Practical Deployment Recommendations <sec:disc-deploy>

The diversity of operating conditions encountered in practice motivates a brief set of deployment guidelines organized by application scenario. For clean photometric edge detection in well-lit, low-noise environments, the recommended configuration is the ASF with rectangular geometric kernels, $sigma_u = 2.0$, $sigma_v = 1.2$, and $N_s = 36$ orientation samples. This setting provides strong localization accuracy with moderate tangential averaging and executes in approximately 45 ms per frame on a modern GPU, suitable for offline or moderately interactive processing.

For applications where the primary objective is semantic boundary detection, including scene parsing, object segmentation, and perceptual grouping, a deep learning model remains the appropriate choice. The ASF does not compete on tasks that require contextual or textural reasoning, and attempting to close the semantic gap through parameter tuning alone is futile.

In noisy environments where the signal-to-noise ratio falls below approximately 10 dB, the ASF with rectangular geometric kernels and scaled $sigma_u$ and $sigma_v$ values is recommended. The continuous parameterization allows the support region to grow in proportion to the noise severity, maintaining detection reliability at the cost of some spatial resolution. This adaptive scaling is the principal advantage over fixed-kernel methods, which offer no mechanism for runtime adjustment, and over deep models, which cannot extend their effective receptive fields beyond what was established during training.

For real-time applications requiring latency below 15 ms per frame, the polynomial ASF variant with $N_p = 25$ neighbors, polynomial order $m = 0$, and $N_s = 4$ orientation samples provides the fastest configuration within the ASF family. The reduced orientation count and small neighborhood sacrifice angular precision and noise robustness but bring the per-frame cost within the budget of time-critical pipelines. Finally, in deployment environments where no GPU is available and computational resources are severely constrained, classical operators such as Sobel or Prewitt remain the pragmatic choice. Their $3 times 3$ kernels execute in microseconds on any hardware and provide adequate gradient estimates when noise is low and spatial precision requirements are modest.
