= Related Work

Edge detection has been studied for over five decades, progressing from simple finite-difference approximations to sophisticated deep learning architectures. This section reviews the three lines of work most relevant to the Anisotropic Stencil Filter: classical gradient operators, deep learning methods, and polynomial fitting filters.

== Classical Gradient Operators

The earliest practical edge detectors are small fixed-coefficient convolution kernels. The Roberts Cross operator @roberts1963blocks applies two $2 times 2$ diagonal difference masks to approximate the gradient along $plus.minus 45 degree$ directions, offering fast computation but high noise sensitivity due to its minimal spatial support. The Prewitt operator @prewitt1970gradient extends the support to $3 times 3$ by averaging along the direction perpendicular to the gradient, producing separate horizontal and vertical derivative estimates that are combined via the Euclidean norm. The Sobel operator @sobel2014history modifies the Prewitt design by placing greater weight on the center row (or column), which introduces a degree of Gaussian-like smoothing perpendicular to the gradient direction and improves noise behavior. Scharr @scharr2000optimal further optimized the $3 times 3$ coefficient structure to minimize angular error under rotation, achieving better rotational symmetry than Sobel at the same kernel size.

Increasing the kernel to $5 times 5$ or $7 times 7$ provides marginal improvements in noise robustness, but the fundamental limitation persists. All of these operators employ a _fixed weight structure_ that cannot adapt to the local image content, edge orientation, or noise level. The gradient angle must be recovered from two cardinal-direction responses via the arctangent function, which introduces systematic angular errors for edges that do not align with the kernel axes.

The Kirsch compass operator @kirsch1971computer takes a different approach by defining eight $3 times 3$ directional kernels (spaced at $45 degree$ intervals) and selecting the maximum response. This represents an early example of _orientation-selective filtering_, where the detector explicitly evaluates multiple candidate edge directions rather than relying on a two-component gradient decomposition. However, the eight discrete orientations and small kernel size limit both angular precision and noise tolerance.

Gaussian derivative filters embed edge detection within the framework of scale-space theory @lindeberg1998edge. By convolving the image with the derivative of a Gaussian kernel at scale $sigma$, one obtains a gradient estimate whose noise robustness is controlled by the smoothing parameter. Lindeberg's automatic scale selection provides a principled mechanism for choosing $sigma$, and the resulting multi-scale analysis has strong theoretical foundations. Nevertheless, the Gaussian kernel is _isotropic_, so smoothing suppresses noise at the cost of blurring edges and displacing fine structures. The Laplacian of Gaussian (LoG) method proposed by Marr and Hildreth @marr1980theory localizes edges as zero-crossings of the second derivative, which guarantees closed contours but amplifies noise and produces spurious edges in textured regions.

The Canny detector @canny1986edge remains the _de facto_ standard classical edge detector. Its multi-stage pipeline consists of Gaussian smoothing, gradient computation, non-maximum suppression (NMS), and hysteresis thresholding. The NMS step thins edges to single-pixel width, and hysteresis connects weak edge fragments that adjoin strong edges. Despite its effectiveness in controlled settings, the Canny detector inherits the smoothing-localization tradeoff from its Gaussian preprocessing stage and the angular errors from its two-direction gradient computation.

Steerable filters, introduced by Freeman and Adelson @freeman1991steerable, provide an elegant mechanism for synthesizing the filter response at any orientation from a small set of _basis filters_. A filter steerable in the $n$-th order requires only $(n+1)$ basis responses to reconstruct the output at an arbitrary angle. This is computationally efficient and analytically exact, but the approach is restricted to filter profiles that can be expressed as a finite Fourier series in orientation, which limits its applicability to sinusoidal or narrow classes of edge profiles.

== Deep Learning Methods

The transition from hand-crafted to learned edge detectors began with Structured Forests @dollar2013structured, in which a random decision forest is trained on local image patches to predict edge probability. By learning non-linear mappings from patch features to edge labels, Structured Forests substantially outperformed classical filters on the BSDS500 benchmark and demonstrated that supervised learning could capture the statistical regularities of natural image boundaries. This approach occupies an important middle ground between classical and deep methods, as it relies on engineered features (gradient histograms, color channels) fed into a learned classifier.

Holistically-Nested Edge Detection (HED) @xie2015hed marked a turning point by applying deep convolutional networks with _deep supervision_ at multiple intermediate layers. Each side output produces an edge map at a different scale, and these are fused to produce the final prediction. The multi-scale feature aggregation allows HED to capture both fine local boundaries and coarse global contours. DexiNed @poma2020biped extended this line of work with a dense extreme inception architecture that requires no ImageNet pre-training, demonstrating that edge-specific architectures can be trained from scratch on relatively small datasets such as BIPED.

Subsequent architectures have pursued either efficiency or novel generative formulations. TEED @soria2023bipedv2 is a tiny and efficient model designed for real-time edge detection with minimal computational overhead while maintaining competitive accuracy. PIDINet @su2021pidinet incorporates _pixel difference convolutions_ that encode traditional gradient computation directly into the network architecture, blending classical edge detection priors with learned feature extraction. NBED @chen2024nbed proposes a neural-network-based architecture specifically designed for boundary extraction with improved thin-edge preservation. DiffusionEdge @ye2024diffusionedge applies diffusion probabilistic models to edge detection, treating edge map generation as a denoising process and producing crisp, well-localized boundaries.

Despite their strong benchmark performance, deep learning methods share several limitations that motivate continued research on non-learned approaches. First, they require _annotated training data_, which is expensive to produce and inevitably encodes the biases of the human annotators. Second, their behavior is _opaque_: the mapping from input pixels to edge predictions is distributed across millions of parameters with no closed-form interpretation. Third, generalization to _unseen domains_ remains problematic. Models trained on natural outdoor images (BSDS500, BIPED) can degrade substantially when applied to underwater, medical, or industrial imagery where the statistical properties of edges differ. Fourth, none of these methods provide _formal gradient guarantees_. The output is a learned probability of boundary presence, not a mathematically grounded estimate of the image gradient magnitude or direction.

== Polynomial Fitting Filters

Bagan and Wang introduced the Weighted Voting Filter (WVF) @bagan2021wvf, which departs from the kernel convolution paradigm by fitting a local polynomial surface to the image intensity. For each pixel, $N_p$ neighbors arranged in an approximately circular pattern are selected, and a two-dimensional polynomial of order $d$ is fitted via weighted least squares. The normal derivative of the fitted surface, evaluated at the center pixel, serves as the gradient estimate. An orientation sweep over $N_s$ candidate angles selects the direction producing the strongest response. The WVF was originally developed for maritime and underwater imaging applications @bagan2024multiscale, where high noise levels and low contrast demand large spatial support for reliable gradient estimation.

The Line Filter (LF) @bagan2023lf extends the WVF by evaluating the polynomial fit at $(2m+1)$ virtual positions displaced along the candidate edge direction and combining the responses via Gaussian-weighted averaging. This _anisotropic extension_ incorporates information from a wider spatial context along the edge tangent, improving coherence and bridging small gaps in edge contours. The recommended parameter configuration ($N_p = 250$, $N_s = 18$, $d = 4$, $m = 14$) reflects the filter's origins in noisy maritime conditions, where maximal spatial support is desirable.

Despite the promising performance of these polynomial fitting filters, several gaps remain in the literature. No systematic optimization of the parameter space ($N_p$, $d$, $m$, $N_s$) has been conducted across standard benchmarks. The computational cost of the naive implementation, which requires $(2m+1) times N_s$ independent polynomial fits per pixel, has precluded real-time or interactive-rate processing. There exists no GPU-native implementation that exploits the parallelism inherent in the per-pixel, per-orientation structure of the computation. Most critically, the _algebraic structure_ of the multi-point weighted combination has not been analyzed. As we show in this paper, the entire line-extended polynomial fitting operation can be collapsed into a single precomputed weight vector per orientation, transforming the filter from a multi-step algorithm into a fixed linear stencil. This insight simultaneously reduces computational cost, clarifies the mathematical nature of the operator, and enables efficient GPU execution.
